version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run: pip install -r requirements.txt
      # Add more steps as needed

workflows:
  version: 2
  build:
    jobs:
      - build
